environment:
  name: prod
  project: cdf-bootcamp-37-prod
  type: prod
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  CDF_PROJECT: cdf-bootcamp-37-prod  # ex. cdf-bootcamp-01-prod
  IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
  IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
  IDP_TENANT_ID: ${IDP_TENANT_ID} # replaced by .env
  # This is related to the cluster where the CDF project is hosted.
  CDF_URL: https://westeurope-1.cognitedata.com
  IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
  IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
  # Groups
  data_developer_source_id: dd8c1f10-9272-4172-bcf7-896c4b00bace
  # OBJECT ID FOR TEST/PROD DATA PIPELINE OEE ENTRA GROUP
  data_pipeline_oee_source_id: 5383a541-7810-41eb-b8ca-41d628bd0bd3
  # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
  readwrite_source_id: 1edc206e-e2a8-4577-843e-7871678e4375
  # OBJECT ID FOR TEST/PROD ADMIN TK ENTRA GROUP
  readonly_source_id: 1edc206e-e2a8-4577-843e-7871678e4375
  # OBJECT ID FOR TEST/PROD ICAPI EXTRACTORS ENTRA GROUP
  icapi_extractors_source_id: 743f1be9-e730-4c95-952e-99290d38e69e
  # Client Ids
  data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
  data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env
  icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
  icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
  # Variables shared by modules
  icapi_ds_external_id: ds_icapi
  uc_oee_ds_external_id: ds_uc_oee